#!/bin/bash

# need to make sure that we get to the correct directory
cd $HOME/Downloads/MyHome/Code/Scripts
if [ `pwd` !eq $HOME/Downloads/MyHome/Code/Scripts ]; then exit; fi

git pull
git status
git add --all
git commit -m "automatic update `date`"
git push
git status
