#!/bin/bash

#This script is used to ssh into Pat's Ubuntu ideapad

if [ $1 == ssh ]; then 
ssh patrick@2601:180:8000:1fe2:fd31:e9a6:9d1c:2d1
fi

if [ $1 == scp ]; then 
echo "scp patrick@2601:180:8000:1fe2:fd31:e9a6:9d1c:2d1$2 $3"
scp patrick@\[2601:180:8000:1fe2:fd31:e9a6:9d1c:2d1\]:$2 $3
fi
