#!/bin/bash

function usage {
    echo "
    a7 = archive as tar.7z
    e7 = extract as tar.7z
    tar = archive to a folder of tarballs 

    use as (commmand option directory) to apply to that directory.
    "
}


if [ $1 = 'a7' ]; then
        starttime=$(date '+%m:%d:%Y-%H:%M:%S')
        name=$(echo $2 | sed 's/\///')
        tar cf bak.$name.$starttime.tar $2
        7za a bak.$name.$starttime.tar.7z bak.$name.$starttime.tar
        rm bak.$name.$starttime.tar
        
elif [ $1 = 'x7' ]; then
    if [ $2 =~ ".tar.7z" ]; then
        usage
        exit
    fi
    7za x $2
    ret=$(echo $2 | sed s/\.7z//)
    tar xf $ret
    rm $ret
    
elif [ $1 = 'tarall' ]; then
    start=$(date '+%m.%d.%Y-%H.%M.%S')
    
    if [ ! -d backup-$start ]; then
        mkdir backup-$start
    fi
    
    parray=()
    for i in *; do 
        if [ $i != 'OS' ] && [[ ! $i =~ "backup-" ]]; then 
            tar cf ./backup-$start/$i.tar $i & 
            echo tarring $i...
            array+=($!)
        fi 
    done
    for i in "${array[@]}"; do
        echo waiting on $i
        wait $i
    done
    echo creating main tar
    time tar cf backup-$start.tar backup-$start
    rm -r backup-$start
    
    echo "Would you like to gzip at this time? (y|n)"; read ret
    if [ $ret = 'y' ]; then
        echo zipping...
        time gzip backup-$start.tar
    else
        echo goodbye
    fi
    
elif [ $1 = 'untarall' ]; then
    for i in *; do
        if [[ $i =~ ".tar" ]]; then
            tar xf $i        
        fi
    done
    
else
    usage
    exit
fi

