#!/bin/bash

master=$(pwd)

#function descend {

depth=4
breadth=3
node_id=0 #for testing, increments +1 each time a folder is created.

# args: level( [0,depth) ), childNo ( [0,breadth) ) 
generateTreeDFS(){
declare -i level=$1
declare -i childNo=$2
declare -i i=0
    if (( $level < $depth ));then
        mkdir "n_level$level-$childNo"
        cd "n_level$level-$childNo"
	touch $node_id
        let node_id++
        let level++

        while [ $i -lt $breadth ]
        do
            generateTreeDFS $level $i
            let i++
        done
        cd ..
    fi
}

generateTreeDFS

: '
subdir=`find . -maxdepth 0 -type d | wc -l`
echo $subdir
if [ $subdir -eq 2 ]
then
    echo "none of interest"
else
    echo "something is in there"
fi

	if [[ -d "" ]]; then echo "there is a directory."; fi

	for i in $(ls -d */)
	do
		echo $i
	done
}'
